### PR TITLE
🚸 Try popup sign in if redirect failed

### PR DESCRIPTION
**Pull request by nwingt**

### CODE REVIEW

**Comment by williamchong007** [comment]
Will user cancel trigger this popup?

**Comment by nwingt** [comment]
closing the window should cancel

**Comment by williamchong007** [comment]
i mean if user cancel in redirect version, a popup will trigger and they will have to press cancel again?

**Comment by nwingt** [comment]
What do you mean by canceling redirect version? By clicking back in browser?

**Comment by williamchong007** [comment]
(actually i just realised there is no cancel button in redirect...)
does it mean we cannot distinguish user cancel or (possible) bug case where user indeed just pressed back button?
not sure if it is considered bad ux if you get a popup everytime you press back

**Comment by nwingt** [comment]
Yes that's the problem

**Pull request merged**
