### PR TITLE
+ Add support for anchors in index

### PR DESCRIPTION
**Pull request by mileswong**

### CODE REVIEW

**Comment by williamchong007** [comment]
package.json 有個 swiper 同 awesome swiper，兩個都係用緊的？

**Comment by mileswong** [comment]
係啊 用左係index 個 carousel

**Comment by williamchong007** [comment]
awesome 同 唔 awesome 果個有咩分別？

**Comment by mileswong** [comment]
updated, removed swiper dependency
awesome has already included it

**Comment by mileswong** [comment]
Updated, remove unnecessary dependecy swiper since it's already included in awesome one 👍🏽

**Pull request merged**
