### PR TITLE
💄 Update text for different Civic Liker status

### PR DESCRIPTION
**Pull request by nwingt**

### CODE REVIEW

**Comment by williamchong007** [comment]
all those `if (true) then return` cases, does that mean we should actually update `civicLikerStatus` to reflect them all in a var

**Comment by nwingt** [comment]
> all those `if (true) then return` cases, does that mean we should actually update `civicLikerStatus` to reflect them all in a var

Maybe like this
- `waiting`
- `trial`
- `subscribed`
- `renewable`
- `expired`

**Comment by williamchong007** [comment]
sounds good, but `subscribed` and `renewable` might overlap?

**Comment by nwingt** [comment]
`subscribed` seems ambiguous 

How about this

* `waiting`
* `trial`
* `paid`
* `renewable`
* `expired`

**Pull request merged**
